ProductCatalog/Models/ErrorViewModel.cs
namespace ProductCatalog.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProductCatalog/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProductCatalog.Models;
using System.Diagnostics;

namespace ProductCatalog.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProductCatalog/Controllers/ProductController.cs

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProductCatalog.BL;

namespace ProductCatalog.MVC.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductsManager _productsManager;
        private readonly ICategoriesManager _categoriesManager;
        public ProductController(IProductsManager productsManager, ICategoriesManager categoriesManager)
        {
            _productsManager = productsManager;
            _categoriesManager = categoriesManager;
        }

        [Authorize(Policy = "Admin")]
        public IActionResult Index()
        {
            ViewData["Categories"] = _categoriesManager.GetAllCategories()
                .Select(c => new SelectListItem(c.CategoryName, c.CategoryId.ToString()))
                .ToList();

            IEnumerable<ProductsReadVM> products = _productsManager.GetAllProducts();
            return View(products);
        }

        [Authorize]
        [HttpGet]
        public IActionResult CurrentProduct()
        {
            ViewData["Categories"] = _categoriesManager.GetAllCategories()
                .Select(c => new SelectListItem(c.CategoryName, c.CategoryId.ToString()))
                .ToList();

            IEnumerable<ProductsReadVM> products = _productsManager.GetCurrentProducts();
            return View(products);
        }

        [Authorize(Policy = "Admin")]
        [HttpGet]
        public IActionResult AddProduct()
        {
            ViewData["Categories"] = _categoriesManager.GetAllCategories()
                .Select(c => new SelectListItem(c.CategoryName, c.CategoryId.ToString()))
                .ToList();

            return View();
        }

        [Authorize(Policy = "Admin")]
        [HttpPost]
        public IActionResult AddProduct(ProductsAddVM productsAddVM)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Categories"] = _categoriesManager.GetAllCategories()
                .Select(c => new SelectListItem(c.CategoryName, c.CategoryId.ToString()))
                .ToList();
                return View();
            }

            var token = Request.Cookies["UserId"];

            _productsManager.AddProduct(productsAddVM, token);
            return RedirectToAction("Index", "Product");
        }

        [Authorize]
        [HttpGet]
        public IActionResult ProductDetails(int id)
        {
            ProductDetailsVM productDetailsVM = _productsManager.GetDetails(id);
            return View(productDetailsVM);
        }

        [Authorize(Policy = "Admin")]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            _productsManager.DeleteProduct(id);
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Policy = "Admin")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ProductEditVM productEditVM = _productsManager.GetToEditProduct(id);

            ViewData["Categories"] = _categoriesManager.GetAllCategories()
                .Select(c => new SelectListItem(c.CategoryName, c.CategoryId.ToString()))
                .ToList();

            return View(productEditVM);
        }

        [Authorize(Policy = "Admin")]
        [HttpPost]
        public IActionResult Edit(ProductEditVM productEditVM)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Categories"] = _categoriesManager.GetAllCategories()
                .Select(c => new SelectListItem(c.CategoryName, c.CategoryId.ToString()))
                .ToList();
                return View();
            }

            _productsManager.EditProduct(productEditVM);
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        [HttpGet]
        public IActionResult ProductFilter(int id)
        {
            ViewData["Categories"] = _categoriesManager.GetAllCategories()
                .Select(c => new SelectListItem(c.CategoryName, c.CategoryId.ToString()))
                .ToList();

            IEnumerable<ProductsReadVM> FilteredProducts = _productsManager.GetFilteredProducts(id);

            return View(FilteredProducts);
        }
    }
}

ProductCatalog/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using ProductCatalog.BL;
using Microsoft.AspNetCore.Http;


namespace ProductCatalog.MVC.Controllers
{
    public class UserController : Controller
    {
        private readonly IUsersManager _usersManager;

        public UserController(IUsersManager usersManager)
        {
            _usersManager = usersManager;
        }


        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(UserRegisterVM userRegisterVM)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var register = await _usersManager.Register(userRegisterVM);

            if (!register.IsSuccess)
            {
                TempData["ErrorMessage"] = register.Message;
                return View();
            }

            return RedirectToAction(nameof(Login));
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserLoginVM userLoginVM)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var response = _usersManager.Login(userLoginVM);
            var Data = await response;

            if(!Data.IsSuccess)
            {
                TempData["ErrorMessage"] = Data.Message;
                return View();
            }

            Response.Cookies.Append("UserId", Data.UserId);

            return RedirectToAction("Index", "Product");
        }

        [HttpPost]
        public IActionResult Logout()
        {
            _usersManager.Logout();
            return RedirectToAction("Login");
        } 
    }
}

ProductCatalog/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProductCatalog/Views/Product/AddProduct.cshtml
@using ProductCatalog.BL;
@model ProductsAddVM
@{
    List<SelectListItem> categories = ViewData["Categories"] as List<SelectListItem> ?? new();
}

<h3 class="text-center">Add New Products</h3>

<form asp-action="AddProduct" method="post">
    <div class="form-group mb-2">
        <label asp-for="productName">Product Name</label>
        <input asp-for="productName" class="form-control" />
        <span class="text-danger" asp-validation-for="productName"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="Price"></label>
        <input asp-for="Price" class="form-control" />
        <span class="text-danger" asp-validation-for="Price"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="StartDate">Start Date</label>
        <input asp-for="StartDate" class="form-control" />
        <span class="text-danger" asp-validation-for="StartDate"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="Duration"></label>
        <input asp-for="Duration" class="form-control" />
        <span class="text-danger" asp-validation-for="Duration"></span>
    </div>
    <div class="form-group mb-2">
        <label class="col-12 col-form-label" asp-for="CategoryId">Category</label>
        <select asp-for="CategoryId" asp-items="categories"></select>
        <span class="text-danger" asp-validation-for="CategoryId"></span>
    </div>
    

    <div class="d-flex justify-content-center">
        <button class="btn btn-primary">Add Product</button>
    </div>
</form>

ProductCatalog/Views/Product/CurrentProduct.cshtml
@using ProductCatalog.BL;

@model IEnumerable<ProductsReadVM>

@{
    List<SelectListItem> categories = ViewData["Categories"] as List<SelectListItem> ?? new();
}

<h3 class="text-center">Current Products</h3>

<form asp-action="ProductFilter" method="get">
    <label for="SelectedCategoryId">Filter by Category</label>
    <select asp-items="categories" name="Id"></select>

    <button class="btn btn-primary">Filter</button>
</form>

<table class="table mt-5">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Product Name</th>
            <th scope="col">Price</th>
            <th scope="col">Category</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var Product in Model)
        {
            <tr>
                <td>@Product.ProductId</td>
                <td>@Product.productName</td>
                <td>@Product.Price</td>
                <td>@Product.Category</td>
                <td>
                    <button class="btn btn-info" onclick="document.location='/product/ProductDetails/@Product.ProductId'">Details</button>
                </td>
            </tr>
        }
    </tbody>
</table>

ProductCatalog/Views/Product/Edit.cshtml
@using ProductCatalog.BL;

@model ProductEditVM

@{
    List<SelectListItem> categories = ViewData["Categories"] as List<SelectListItem> ?? new();
}

<h3 class="text-center">Edit Product</h3>

<form asp-action="Edit" method="post">

    <input type="hidden" asp-for="ProductId" />

    <div class="form-group mb-2">
        <label asp-for="productName">Product Name</label>
        <input asp-for="productName" class="form-control" />
        <span class="text-danger" asp-validation-for="productName"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="Price"></label>
        <input asp-for="Price" class="form-control" />
        <span class="text-danger" asp-validation-for="Price"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="StartDate">Start Date</label>
        <input asp-for="StartDate" class="form-control" />
        <span class="text-danger" asp-validation-for="StartDate"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="Duration"></label>
        <input asp-for="Duration" class="form-control" />
        <span class="text-danger" asp-validation-for="Duration"></span>
    </div>
    <div class="form-group mb-2">
        <label class="col-12 col-form-label" asp-for="CategoryId">Category</label>
        <select asp-for="CategoryId" asp-items="categories"></select>
        <span class="text-danger" asp-validation-for="CategoryId"></span>
    </div>


    <div class="d-flex justify-content-center">
        <button class="btn btn-primary">Edit Product</button>
    </div>
</form>

ProductCatalog/Views/Product/Index.cshtml
@using ProductCatalog.BL;

@model IEnumerable<ProductsReadVM>

@{
    List<SelectListItem> categories = ViewData["Categories"] as List<SelectListItem> ?? new();
}

<h3 class="text-center">Products</h3>

<div class="d-flex justify-content-end">
    <button class="btn btn-primary" onclick="document.location='/product/addproduct'">Add new Product</button>
</div>

<form asp-action="ProductFilter" method="get">
    <label for="SelectedCategoryId">Filter by Category</label>
    <select asp-items="categories" name="Id"></select>

    <button class="btn btn-primary">Filter</button>
</form>

<table class="table mt-5">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Product Name</th>
            <th scope="col">Price</th>
            <th scope="col">Category</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var Product in Model)
        {
            <tr>
                <td>@Product.ProductId</td>
                <td>@Product.productName</td>
                <td>@Product.Price</td>
                <td>@Product.Category</td>
                <td>
                    <button class="btn btn-info" onclick="document.location='/product/ProductDetails/@Product.ProductId'">Details</button>
                </td>
                <td>
                    <button class="btn btn-primary" onclick="document.location='/product/edit/@Product.ProductId'">Edit</button>
                </td>
                <td>
                    <form asp-action="Delete" asp-route-id="@Product.ProductId" method="post" id="deleteButton">
                        <button class="btn btn-danger" type="button" onclick="confirmDelete()">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts{
    <partial name="_ConfirmDeletePartial.cshtml" />
}

ProductCatalog/Views/Product/ProductDetails.cshtml
@using ProductCatalog.BL;
@model ProductDetailsVM

<table class="table mt-5">
    <tbody>
        <tr>
            <th scope="col">#Id</th>
            <td>@Model.ProductId</td>
        </tr>
        <tr>
            <th scope="col">Product Name</th>
            <td>@Model.productName</td>
        </tr>
        <tr>
            <th scope="col">Price</th>
            <td>@Model.Price</td>
        </tr>
        <tr>
            <th scope="col">Category</th>
            <td>@Model.Category</td>
        </tr>
        <tr>
            <th scope="col">Creation Date</th>
            <td>@Model.CreationDate</td>
        </tr>
        <tr>
            <th scope="col">Start Date</th>
            <td>@Model.StartDate</td>
        </tr>
        <tr>
            <th scope="col">Duration</th>
            <td>@Model.Duration</td>
        </tr>
        <tr>
            <th scope="col">Created By</th>
            <td>@Model.CreatedBy</td>
        </tr>
    </tbody>
</table>

ProductCatalog/Views/Product/ProductFilter.cshtml
@using ProductCatalog.BL;

@model IEnumerable<ProductsReadVM>

@{
    List<SelectListItem> categories = ViewData["Categories"] as List<SelectListItem> ?? new();
}

<h3 class="text-center">Products</h3>

<div class="d-flex justify-content-end">
    <button class="btn btn-primary" onclick="document.location='/product/addproduct'">Add new Product</button>
</div>

<form asp-action="ProductFilter" method="get">
    <label for="SelectedCategoryId">Filter by Category</label>
    <select asp-items="categories" name="Id"></select>

    <button class="btn btn-primary">Filter</button>
</form>

<table class="table mt-5">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Product Name</th>
            <th scope="col">Price</th>
            <th scope="col">Category</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var Product in Model)
        {
            <tr>
                <td>@Product.ProductId</td>
                <td>@Product.productName</td>
                <td>@Product.Price</td>
                <td>@Product.Category</td>
                <td>
                    <button class="btn btn-info" onclick="document.location='/product/ProductDetails/@Product.ProductId'">Details</button>
                </td>
                <td>
                    <button class="btn btn-primary" onclick="document.location='/product/edit/@Product.ProductId'">Edit</button>
                </td>
                <td>
                    <form asp-action="Delete" asp-route-id="@Product.ProductId" method="post" id="deleteButton">
                        <button class="btn btn-danger" type="button" onclick="confirmDelete()">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts{
    <partial name="_ConfirmDeletePartial.cshtml" />
}

ProductCatalog/Views/Shared/_ConfirmDeletePartial.cshtml
<script>
    function confirmDelete() {
        if (confirm("Are you sure you want to delete this?")) {
            var form = document.getElementById('deleteButton');
            form.submit();
        }
    }
</script>

ProductCatalog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductCatalog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductCatalog.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="product" asp-action="Index">ProductCatalog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="product" asp-action="Index">All products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="product" asp-action="currentproduct">Current products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="user" asp-action="login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="user" asp-action="register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="user" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProductCatalog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProductCatalog/Views/User/Login.cshtml
@using ProductCatalog.BL;
@model UserLoginVM

<h3 class="text-center">Login</h3>

@if (TempData.ContainsKey("ErrorMessage"))
{
    <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
}

<form asp-action="Login" method="post">
    <div class="form-group mb-2">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
        <span class="text-danger" asp-validation-for="Email"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="Password"></label>
        <input type="password" asp-for="Password" class="form-control" />
        <span class="text-danger" asp-validation-for="Password"></span>
    </div>

    <p>Don't have account ? <a href="@Url.Action("Register", "User")">Register Now</a></p>
    
    <button class="btn btn-primary">Login</button>
</form>

ProductCatalog/Views/User/Register.cshtml
@using ProductCatalog.BL;
@model UserRegisterVM

<h3 class="text-center">Register Now</h3>

@if (TempData.ContainsKey("ErrorMessage"))
{
    <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
}

<form asp-action="Register" method="post">
    <div class="form-group mb-2">
        <label asp-for="FName">First Name</label>
        <input asp-for="FName" class="form-control" />
        <span class="text-danger" asp-validation-for="FName"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="LName">Last Name</label>
        <input asp-for="LName" class="form-control" />
        <span class="text-danger" asp-validation-for="LName"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
        <span class="text-danger" asp-validation-for="Email"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="Age"></label>
        <input asp-for="Age" class="form-control" />
        <span class="text-danger" asp-validation-for="Age"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="Password"></label>
        <input type="password" asp-for="Password" class="form-control" />
        <span class="text-danger" asp-validation-for="Password"></span>
    </div>

    <button class="btn btn-primary">Register</button>
</form>